name: Run Python script on Push

on:
  pull_request:
    branches:
      - dev

jobs:
  run-python-test1:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        id: run_test1
        run: |
          python3 test.py || echo "test1_failed=true" >> $GITHUB_ENV

      - name: Set Test1 Status
        id: test1_status
        run: echo "::set-output name=test1_failed::$test1_failed"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report1
          path: ./test-reports/TEST-TestMathOperations-test-report1.xml

    outputs:
      test1_failed: ${{ steps.test1_status.outputs.test1_failed }}

  run-python-test2:
    needs: run-python-test1
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        id: run_test2
        run: |
          python3 test2.py || echo "test2_failed=true" >> $GITHUB_ENV

      - name: Set Test2 Status
        id: test2_status
        run: echo "::set-output name=test2_failed::$test2_failed"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report2
          path: ./test-reports/TEST-TestMathOperations-test-report2.xml

    outputs:
      test2_failed: ${{ steps.test2_status.outputs.test2_failed }}

  send-email-report:
    needs: [run-python-test1, run-python-test2]
    runs-on: ubuntu-latest

    steps:
      - name: Download All Test Reports
        if: always()
        uses: actions/download-artifact@v2

      - name: Set Mail Body
        id: mail_body
        run: |
          BODY="Build job of ${{ github.repository }} completed successfully!"

          if [ "${{ needs.run-python-test1.outputs.test1_failed }}" == "true" ]; then
            BODY="Build job not completed because of test1 fail."
          fi

          if [ "${{ needs.run-python-test2.outputs.test2_failed }}" == "true" ]; then
            BODY="${BODY} Test2 also failed."
          fi

          echo "Final Mail Body: $BODY"
          echo "mail_body=$BODY" >> $GITHUB_ENV

      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Github Actions job result
          from: yuri allam
          to: youry.allam@net.usj.edu.lb
          body: ${{ env.mail_body }}
          ignore_cert: true
          convert_markdown: true
          attachments: ./test-report1/TEST-TestMathOperations-test-report1.xml,./test-report2/TEST-TestMathOperations-test-report2.xml
          priority: low
