name: Run Python script on Push

on:
  pull_request:
    branches:
      - dev

jobs:
  run-python-test1:
    runs-on: self-hosted
    continue-on-error: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        id: run_test1
        run: python3 test.py

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report1
          path: ./test-reports/TEST-TestMathOperations-test-report1.xml

    outputs:
      job1_status: ${{ job.status }}

  run-python-test2:
    runs-on: self-hosted
    needs: run-python-test1
    continue-on-error: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        id: run_test2
        run: python3 test2.py

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report2
          path: ./test-reports/TEST-TestMathOperations-test-report2.xml

    outputs:
      job2_status: ${{ job.status }}

  send-email-report:
    needs: [run-python-test1, run-python-test2]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download All Test Reports
        uses: actions/download-artifact@v2

      - name: Set Mail Body
        id: mail_body
        run: |
          BODY="Build job of ${{ github.repository }} completed successfully!"

          if [ "${{ needs.run-python-test1.outputs.job1_status }}" != "Success" ]; then
            BODY="Build job not completed because of test1 fail."
          fi

          if [ "${{ needs.run-python-test2.outputs.job2_status }}" != "Success" ]; then
            BODY="${BODY} Test2 also failed."
          fi

          echo "Final Mail Body: $BODY"
          echo "mail_body=$BODY" >> $GITHUB_ENV

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Github Actions job result
          from: yuri allam
          to: youry.allam@net.usj.edu.lb
          body: ${{ env.mail_body }}
          ignore_cert: true
          convert_markdown: true
          attachments: ./test-report1/TEST-TestMathOperations-test-report1.xml,./test-report2/TEST-TestMathOperations-test-report2.xml
          priority: low
