name: Run Python script on Push

on:
  pull_request:
    branches:
      - dev

jobs:
  run-python-test1:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python3 test.py
  run-python-test1:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python3 test2.py
  