name: Run Python script on Push

on:
  pull_request:
    branches:
      - dev

jobs:
  run-python-test1:
    runs-on: self-hosted
    continue-on-error: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python3 test.py

      - name: Determine Job Status
        id: job1_status
        run: echo "success" > job1_status.txt

      - name: Upload status as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: job1_status
          path: ./job1_status.txt

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report1
          path: ./test-reports/TEST-TestMathOperations-test-report1.xml

    outputs:
      job1_status: ${{ steps.job1_status.outputs.job1_status }}

  run-python-test2:
    needs: run-python-test1
    runs-on: self-hosted
    continue-on-error: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python3 test2.py

      - name: Determine Job Status
        id: job2_status
        run: echo "success" > job2_status.txt

      - name: Upload status as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: job2_status
          path: ./job2_status.txt

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report2
          path: ./test-reports/TEST-TestMathOperations-test-report2.xml

    outputs:
      job2_status: ${{ steps.job2_status.outputs.job2_status }}

  send-email-report:
    needs: [run-python-test1, run-python-test2]
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v2

      - name: Determine Email Body
        run: |
          JOB1_STATUS=$(cat job1_status/job1_status.txt)
          JOB2_STATUS=$(cat job2_status/job2_status.txt)
          BODY="Build job of ${{ github.repository }} completed successfully!"

          if [ "$JOB1_STATUS" != "success" ]; then
            BODY="Build job not completed. Test1 fail"
          fi

          if [ "$JOB2_STATUS" != "success" ]; then
            BODY="${BODY}. Test2 also failed."
          fi

          echo "Final Mail Body: $BODY"
          echo "mail_body=$BODY" >> $GITHUB_ENV

        - name: Send mail
          if: always()
          uses: dawidd6/action-send-mail@v3
          with:
            connection_url: ${{secrets.MAIL_CONNECTION}}
            subject: Github Actions job result
            from: yuri allam
            to: youry.allam@net.usj.edu.lb
            body: ${{ env.mail_body }}
            ignore_cert: true
            convert_markdown: true
            attachments: ./test-report1/TEST-TestMathOperations-test-report1.xml,./test-report2/TEST-TestMathOperations-test-report2.xml
            priority: low