name: Run Python script on Push

on:
  pull_request:
    branches:
      - dev

jobs:
  run-python-test1:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python3 test.py
        continue-on-error: true

  run-python-test2:
    needs: run-python-test1
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python3 test2.py
        continue-on-error: true

  send-email-report:
    needs: [run-python-test1, run-python-test2]
    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Github Actions job result
          from: yuri allam
          to: youry.allam@net.usj.edu.lb
          body: Build job of ${{github.repository}} completed successfully!
          ignore_cert: true
          convert_markdown: true
          attachments: ./test-reports/TEST-TestMathOperations-test-report1.xml,./test-reports/TEST-TestMathOperations-test-report2.xml
          priority: low
